name: "Update Hub"

on:
  repository_dispatch:
    types: ["update-hub"]

jobs:
  Update-Hub:
    runs-on: ubuntu-latest
    steps:
      - name: "Update Hub"
        uses: cephalofair-games-llc/rules-actions/update-hub@v1.0
        with:
          source: ${{ github.event.client_payload.source }}
          author: ${{ github.event.client_payload.author }}
          commit: ${{ github.event.client_payload.commit }}
          pat: ${{ secrets.PAT }}
